const jsonList = [
  {
    "name": "SON Putri",
    "prodigy": "Nordenium",
    "recipient": "Roomate Asiquy",
    "message": "Roommatekuuuuuuuuuu semangatttttt, aku sayang kalian ututu @BAE Aera @NA Flo @SEO Matcha",
    "HomeLivingSet": true,
    "ElectronicSet": true,
    "AccessoriesSet": true,
    "StationarySet": true,
    "PCSet1": true,
    "PCSet2": true,
    "Headphone": true,
    "PassportCover": true,
    "LaptopCover": true,
    "NightstandLamp": true,
    "ComfortCushion": true,
    "TCWW1": false,
    "TCWW2": true
  },
  {
    "name": "SEO Matcha",
    "prodigy": "Nordenium",
    "recipient": "Lee ocha",
    "message": "Ochaa, makasiii ya udh jadi temen aca huhu syg oca💙",
    "HomeLivingSet": false,
    "ElectronicSet": false,
    "AccessoriesSet": true,
    "StationarySet": false,
    "PCSet1": false,
    "PCSet2": true,
    "Headphone": false,
    "PassportCover": false,
    "LaptopCover": false,
    "NightstandLamp": false,
    "ComfortCushion": false,
    "TCWW1": false,
    "TCWW2": false
  },
  {
    "name": "NA Disya",
    "prodigy": "Vestenium",
    "recipient": "rumah jmetie (pliharaanku)",
    "message": "lop yu jmetie🤩🤟",
    "HomeLivingSet": true,
    "ElectronicSet": true,
    "AccessoriesSet": true,
    "StationarySet": true,
    "PCSet1": true,
    "PCSet2": true,
    "Headphone": true,
    "PassportCover": true,
    "LaptopCover": true,
    "NightstandLamp": true,
    "ComfortCushion": true,
    "TCWW1": true,
    "TCWW2": false
  },
  {
    "name": "RYU Ziraa",
    "prodigy": "Vestenium",
    "recipient": "All",
    "message": "💙💙💙💙💙💙💙💙💙",
    "HomeLivingSet": false,
    "ElectronicSet": true,
    "AccessoriesSet": false,
    "StationarySet": false,
    "PCSet1": true,
    "PCSet2": false,
    "Headphone": true,
    "PassportCover": false,
    "LaptopCover": true,
    "NightstandLamp": true,
    "ComfortCushion": false,
    "TCWW1": false,
    "TCWW2": true
  },
  {
    "name": "Ryu Yangyang",
    "prodigy": "Nordenium",
    "recipient": "Park Hyejin",
    "message": "Ini tanda pertemanan, gausah ngajak berantem lagi. kalo ngajak berantem lagi balikin hadiah dari gue!",
    "HomeLivingSet": false,
    "ElectronicSet": false,
    "AccessoriesSet": false,
    "StationarySet": true,
    "PCSet1": false,
    "PCSet2": false,
    "Headphone": false,
    "PassportCover": false,
    "LaptopCover": false,
    "NightstandLamp": false,
    "ComfortCushion": false,
    "TCWW1": false,
    "TCWW2": true
  },
  {
    "name": "PARK Jane",
    "prodigy": "Sydenium",
    "recipient": "Sydenium",
    "message": "OH TADI ITU BUAT SIAPA YA BUKAN KEMANA EH APA GMN SIH.... gue agak bingung sorry gue badut meng gapapa gausah diwaro 😭",
    "HomeLivingSet": true,
    "ElectronicSet": true,
    "AccessoriesSet": true,
    "StationarySet": true,
    "PCSet1": true,
    "PCSet2": true,
    "Headphone": true,
    "PassportCover": true,
    "LaptopCover": true,
    "NightstandLamp": true,
    "ComfortCushion": true,
    "TCWW1": true,
    "TCWW2": false
  },
  {
    "name": "Aku Siapa👀",
    "prodigy": "Nordenium",
    "recipient": "Staff nordanus, Ryu Yangyang, Lee Haechan, HRD N, Semua anak norde, Yoon Charis (Vestenium), Lee Lilix (Vestenium)",
    "message": "BAHAGIA DAN SEMANGAT SELALU \\(^v^)/",
    "HomeLivingSet": true,
    "ElectronicSet": true,
    "AccessoriesSet": false,
    "StationarySet": false,
    "PCSet1": false,
    "PCSet2": true,
    "Headphone": false,
    "PassportCover": false,
    "LaptopCover": false,
    "NightstandLamp": true,
    "ComfortCushion": false,
    "TCWW1": true,
    "TCWW2": false
  },
  {
    "name": "LEE Haidar",
    "prodigy": "Ostenium",
    "recipient": "Prodigyzen",
    "message": "you've work hard, prodigyzen!",
    "HomeLivingSet": false,
    "ElectronicSet": false,
    "AccessoriesSet": false,
    "StationarySet": true,
    "PCSet1": true,
    "PCSet2": false,
    "Headphone": true,
    "PassportCover": true,
    "LaptopCover": true,
    "NightstandLamp": true,
    "ComfortCushion": true,
    "TCWW1": false,
    "TCWW2": true
  },
  {
    "name": "KWON Agy",
    "prodigy": "Sydenium",
    "recipient": "Park Cally, Sydenium",
    "message": "Hi, Bu ketipak ketipuk!\nNih udah agy beliin yaa! Terus mau menyampaikan pesan dari lubuk hati yang paling dalam, terimakasih sudah mau bekerja keras buat kita semua( ◜‿◝ )♡ Mau peluk cally banyak banyaaaaaaaaaak♥️ \n\nLove, peace and gawl🤘",
    "HomeLivingSet": true,
    "ElectronicSet": false,
    "AccessoriesSet": true,
    "StationarySet": false,
    "PCSet1": true,
    "PCSet2": true,
    "Headphone": false,
    "PassportCover": false,
    "LaptopCover": false,
    "NightstandLamp": true,
    "ComfortCushion": true,
    "TCWW1": false,
    "TCWW2": true
  },
  {
    "name": "Lee keisha a",
    "prodigy": "Nordenium",
    "recipient": "Kamar keyi dongs",
    "message": "Apa ya.... gatau terserah aja",
    "HomeLivingSet": false,
    "ElectronicSet": false,
    "AccessoriesSet": false,
    "StationarySet": true,
    "PCSet1": false,
    "PCSet2": true,
    "Headphone": false,
    "PassportCover": false,
    "LaptopCover": false,
    "NightstandLamp": true,
    "ComfortCushion": false,
    "TCWW1": false,
    "TCWW2": true
  },
  {
    "name": "LEE Tessya",
    "prodigy": "Nordenium",
    "recipient": "Staff Nordanus",
    "message": "Terima kasih atas kerja kerasnya... Maafin aku kalo aku menyusahkan kalian para danus, i lop yu pul",
    "HomeLivingSet": true,
    "ElectronicSet": true,
    "AccessoriesSet": true,
    "StationarySet": true,
    "PCSet1": true,
    "PCSet2": false,
    "Headphone": true,
    "PassportCover": true,
    "LaptopCover": true,
    "NightstandLamp": true,
    "ComfortCushion": true,
    "TCWW1": true,
    "TCWW2": false
  },
  {
    "name": "Aku siapa👀",
    "prodigy": "Nordenium",
    "recipient": "Staff nordanus, ryu yangyang, lee haechan, semua anak norde, HRD, yoon charis dan lee lilix (vestenium)",
    "message": "Bahagia dan semangat selalu ya \\(^v^)/",
    "HomeLivingSet": true,
    "ElectronicSet": true,
    "AccessoriesSet": false,
    "StationarySet": false,
    "PCSet1": false,
    "PCSet2": true,
    "Headphone": false,
    "PassportCover": false,
    "LaptopCover": false,
    "NightstandLamp": true,
    "ComfortCushion": false,
    "TCWW1": true,
    "TCWW2": false
  },
  {
    "name": "MR. LEE Gochujang",
    "prodigy": "Nordenium",
    "recipient": "Miss CHOI Hyo Min, Nordenium Room. Ketua Danusan NORDANUS",
    "message": "Miss Hyo,thank you udah buat NORDANUS sekeren ini dan thank you juga udah ngeluangin waktunya buat ngurusin NORDANUS thank you so much ini keren banget. Semangat terus ya Hyo dan harus sabar sabar juga ngadepin tim danusan yang super aneh ituuuu kelakuannya. Intinya mau terima kasih aja sama Miss Hyo. Salam anjay 💙🤟",
    "HomeLivingSet": true,
    "ElectronicSet": false,
    "AccessoriesSet": true,
    "StationarySet": false,
    "PCSet1": true,
    "PCSet2": false,
    "Headphone": true,
    "PassportCover": false,
    "LaptopCover": false,
    "NightstandLamp": true,
    "ComfortCushion": false,
    "TCWW1": false,
    "TCWW2": true
  },
  {
    "name": "LEE Vivian",
    "prodigy": "Sydenium",
    "recipient": "CHO Fiona - Vestenium",
    "message": "Love you monyet wakanda",
    "HomeLivingSet": false,
    "ElectronicSet": false,
    "AccessoriesSet": true,
    "StationarySet": false,
    "PCSet1": true,
    "PCSet2": false,
    "Headphone": true,
    "PassportCover": false,
    "LaptopCover": false,
    "NightstandLamp": false,
    "ComfortCushion": false,
    "TCWW1": false,
    "TCWW2": true
  },
  {
    "name": "LEE Gochujang",
    "prodigy": "Nordenium",
    "recipient": "PARK Aruna (Barney mangap) room",
    "message": "Thank you Aruna, Kamu wangi...\nGood luck in nordenium yaaa\nSee you when i see you hahahaha\nL",
    "HomeLivingSet": false,
    "ElectronicSet": false,
    "AccessoriesSet": false,
    "StationarySet": true,
    "PCSet1": true,
    "PCSet2": false,
    "Headphone": false,
    "PassportCover": true,
    "LaptopCover": false,
    "NightstandLamp": false,
    "ComfortCushion": false,
    "TCWW1": true,
    "TCWW2": false
  },
  {
    "name": "LEE Asdos Gochujang",
    "prodigy": "Nordenium",
    "recipient": "PARK Julie Room.",
    "message": "Julie gue udah kehabisan kata kataaaa jadi,\nThank u for alive\nGood luck in NPA\nSee you when i see you",
    "HomeLivingSet": false,
    "ElectronicSet": true,
    "AccessoriesSet": false,
    "StationarySet": false,
    "PCSet1": false,
    "PCSet2": true,
    "Headphone": false,
    "PassportCover": false,
    "LaptopCover": true,
    "NightstandLamp": false,
    "ComfortCushion": false,
    "TCWW1": false,
    "TCWW2": true
  },
  {
    "name": "LEE Ziliya",
    "prodigy": "Nordenium",
    "recipient": "Norde hall",
    "message": "Dear my beloved nordenium! This is for yoy guys",
    "HomeLivingSet": false,
    "ElectronicSet": false,
    "AccessoriesSet": false,
    "StationarySet": true,
    "PCSet1": true,
    "PCSet2": false,
    "Headphone": true,
    "PassportCover": false,
    "LaptopCover": false,
    "NightstandLamp": false,
    "ComfortCushion": false,
    "TCWW1": false,
    "TCWW2": true
  },
  {
    "name": "LEE Asdos Gochujang",
    "prodigy": "Nordenium",
    "recipient": "PARK Arra, Nordenium Room",
    "message": "Arra,makasih ya udah jadi tempat ngobrol² materi hahaha seneng ada yang dijadiin tempat naro materi. Arra ayo semangat!!",
    "HomeLivingSet": false,
    "ElectronicSet": false,
    "AccessoriesSet": false,
    "StationarySet": true,
    "PCSet1": true,
    "PCSet2": false,
    "Headphone": false,
    "PassportCover": false,
    "LaptopCover": false,
    "NightstandLamp": false,
    "ComfortCushion": true,
    "TCWW1": false,
    "TCWW2": true
  },
  {
    "name": "LEE Gochujang",
    "prodigy": "Nordenium",
    "recipient": "My Mitra kerja,wangi sekebon bunga LEE Cireng rooms",
    "message": "Cireng,gue udah gatau mau ngomong apa lagi iniiii yang jelas LU WANGI ANJIRRRR pusing gue liatnyaaa dah itu aja... Jangan lupa gue asdos norde contekan gue yang megang semua hahahahaha",
    "HomeLivingSet": false,
    "ElectronicSet": false,
    "AccessoriesSet": false,
    "StationarySet": true,
    "PCSet1": false,
    "PCSet2": true,
    "Headphone": false,
    "PassportCover": false,
    "LaptopCover": true,
    "NightstandLamp": false,
    "ComfortCushion": false,
    "TCWW1": true,
    "TCWW2": false
  },
  {
    "name": "LEE Gochujang",
    "prodigy": "Nordenium",
    "recipient": "Hwang Sasa Room",
    "message": "Sasa,mau berterima kasih banyak terus mau minta maaf kalo gue punya salah. Mau kenal lebih Deket sama semuanya cuma 1² jadi ayo berteman!!! 💙🤟",
    "HomeLivingSet": false,
    "ElectronicSet": false,
    "AccessoriesSet": true,
    "StationarySet": false,
    "PCSet1": true,
    "PCSet2": false,
    "Headphone": false,
    "PassportCover": false,
    "LaptopCover": false,
    "NightstandLamp": false,
    "ComfortCushion": true,
    "TCWW1": true,
    "TCWW2": false
  },
  {
    "name": "LEE Gochujang",
    "prodigy": "Nordenium",
    "recipient": "Asrama perempuan norde",
    "message": "Thank you udah mau jadi pendengar yang baik dan partner gua yang baik,dan ngeluangin waktunya buat dengerin cerita gua. Thank you💙",
    "HomeLivingSet": true,
    "ElectronicSet": false,
    "AccessoriesSet": true,
    "StationarySet": false,
    "PCSet1": false,
    "PCSet2": true,
    "Headphone": false,
    "PassportCover": false,
    "LaptopCover": false,
    "NightstandLamp": false,
    "ComfortCushion": true,
    "TCWW1": true,
    "TCWW2": false
  },
  {
    "name": "LEE Dira",
    "prodigy": "Nordenium",
    "recipient": "Panitia",
    "message": "mau kasih buat panitia danusan yang udah ngeluangin waktunya buat nordanus ini, sama mau ngasih tau aja kalau you all did well. you all did amazing. you all did your best. mungkin kalian gatau aku karena aku jarang banget nongol di grup tapi aku selalu mantau kalian kok. Semoga acaranya lancar ya dan apa yang telah diperjuangkan dan yang diusahakan membuahkan hasil yang baik. SEMANGAT TIM NORDANUS, I NORDE U ALL💙💙💙",
    "HomeLivingSet": true,
    "ElectronicSet": true,
    "AccessoriesSet": true,
    "StationarySet": true,
    "PCSet1": true,
    "PCSet2": false,
    "Headphone": false,
    "PassportCover": false,
    "LaptopCover": false,
    "NightstandLamp": false,
    "ComfortCushion": false,
    "TCWW1": false,
    "TCWW2": true
  },
  {
    "name": "LEE Jena",
    "prodigy": "Sydenium",
    "recipient": "Ostenium building",
    "message": "Untuk Choi Ryn dan sepupu Choi yang lain♡",
    "HomeLivingSet": true,
    "ElectronicSet": true,
    "AccessoriesSet": true,
    "StationarySet": true,
    "PCSet1": true,
    "PCSet2": true,
    "Headphone": true,
    "PassportCover": true,
    "LaptopCover": true,
    "NightstandLamp": true,
    "ComfortCushion": true,
    "TCWW1": false,
    "TCWW2": true
  },
  {
    "name": "KWON Agy",
    "prodigy": "Sydenium",
    "recipient": "LEE Haechan, Nordenium",
    "message": "(◍•ᴗ•◍)",
    "HomeLivingSet": false,
    "ElectronicSet": true,
    "AccessoriesSet": false,
    "StationarySet": true,
    "PCSet1": false,
    "PCSet2": true,
    "Headphone": true,
    "PassportCover": false,
    "LaptopCover": true,
    "NightstandLamp": false,
    "ComfortCushion": false,
    "TCWW1": false,
    "TCWW2": false
  },
  {
    "name": "LEE Yeseul",
    "prodigy": "Nordenium",
    "recipient": "G221",
    "message": "untuk semua tim danusan~",
    "HomeLivingSet": true,
    "ElectronicSet": false,
    "AccessoriesSet": true,
    "StationarySet": false,
    "PCSet1": false,
    "PCSet2": true,
    "Headphone": false,
    "PassportCover": false,
    "LaptopCover": true,
    "NightstandLamp": false,
    "ComfortCushion": false,
    "TCWW1": false,
    "TCWW2": true
  },
  {
    "name": "Park Cally",
    "prodigy": "Sydenium",
    "recipient": "My dorm, 1234",
    "message": "Hai, Cally, please love yourself. XOXO.",
    "HomeLivingSet": false,
    "ElectronicSet": true,
    "AccessoriesSet": false,
    "StationarySet": false,
    "PCSet1": false,
    "PCSet2": true,
    "Headphone": true,
    "PassportCover": true,
    "LaptopCover": true,
    "NightstandLamp": true,
    "ComfortCushion": false,
    "TCWW1": false,
    "TCWW2": true
  },
  {
    "name": "you know who",
    "prodigy": "Nordenium",
    "recipient": "lee badut yakult proposal yeseul dorm",
    "message": "thank you for your hard work today! ayo liburan!!! ",
    "HomeLivingSet": false,
    "ElectronicSet": false,
    "AccessoriesSet": true,
    "StationarySet": false,
    "PCSet1": true,
    "PCSet2": true,
    "Headphone": true,
    "PassportCover": false,
    "LaptopCover": false,
    "NightstandLamp": false,
    "ComfortCushion": true,
    "TCWW1": false,
    "TCWW2": false
  },
  {
    "name": "KIM Elena",
    "prodigy": "Vestenium",
    "recipient": "KIM Araseli, CHO Fiona, SEO Alexa, KWON Chessa",
    "message": "gak nyesel gue ketemu kalian, soalnya kalian jmtieeee",
    "HomeLivingSet": true,
    "ElectronicSet": false,
    "AccessoriesSet": false,
    "StationarySet": false,
    "PCSet1": false,
    "PCSet2": true,
    "Headphone": false,
    "PassportCover": false,
    "LaptopCover": false,
    "NightstandLamp": true,
    "ComfortCushion": false,
    "TCWW1": false,
    "TCWW2": true
  },
  {
    "name": "KIM Yura",
    "prodigy": "Vestenium",
    "recipient": "The Kim",
    "message": "I want to give this to the Kim who's been cheering me on",
    "HomeLivingSet": false,
    "ElectronicSet": true,
    "AccessoriesSet": false,
    "StationarySet": false,
    "PCSet1": true,
    "PCSet2": false,
    "Headphone": false,
    "PassportCover": false,
    "LaptopCover": true,
    "NightstandLamp": false,
    "ComfortCushion": false,
    "TCWW1": false,
    "TCWW2": true
  },
  {
    "name": "Na Ally",
    "prodigy": "Vestenium",
    "recipient": "All",
    "message": "Semuanya, tolong doakan almarhum cimit tenang disana ya 🙏🏻 semoga arwahnya ngga gentayangan.. terimakasih doanya ya 🙏🏻😭",
    "HomeLivingSet": true,
    "ElectronicSet": true,
    "AccessoriesSet": true,
    "StationarySet": false,
    "PCSet1": true,
    "PCSet2": false,
    "Headphone": false,
    "PassportCover": false,
    "LaptopCover": false,
    "NightstandLamp": true,
    "ComfortCushion": true,
    "TCWW1": true,
    "TCWW2": false
  },
  {
    "name": "HWANG Cia",
    "prodigy": "Vestenium",
    "recipient": "rumah mamang",
    "message": "mamang yang bener dong kalo jagain pet veste 😭😭 semoga menjadi pribadi yg lebih baik lg dalam menjaga hutan dan pet anak veste. mangat yh mamang",
    "HomeLivingSet": true,
    "ElectronicSet": true,
    "AccessoriesSet": true,
    "StationarySet": false,
    "PCSet1": true,
    "PCSet2": false,
    "Headphone": true,
    "PassportCover": true,
    "LaptopCover": true,
    "NightstandLamp": true,
    "ComfortCushion": true,
    "TCWW1": false,
    "TCWW2": true
  },
  {
    "name": "LEE Bupy",
    "prodigy": "Vestenium",
    "recipient": "Pls send it to LEE Felix",
    "message": "buat papa felix, ini bupy beliin >< semoga papa suka ya!",
    "HomeLivingSet": true,
    "ElectronicSet": false,
    "AccessoriesSet": false,
    "StationarySet": false,
    "PCSet1": true,
    "PCSet2": false,
    "Headphone": true,
    "PassportCover": true,
    "LaptopCover": true,
    "NightstandLamp": true,
    "ComfortCushion": true,
    "TCWW1": true,
    "TCWW2": false
  },
  {
    "name": "LEE Gochujang",
    "prodigy": "Nordenium",
    "recipient": "LEE Tessya Room Nordenium hahahaha",
    "message": "Coyy gue capek sejujurnyaa cuma karna lu partner ww guee jadi ya gue mau berterima kasih sama luu udah jadi partner ww terdabest 💙🤟",
    "HomeLivingSet": false,
    "ElectronicSet": false,
    "AccessoriesSet": true,
    "StationarySet": false,
    "PCSet1": false,
    "PCSet2": true,
    "Headphone": false,
    "PassportCover": false,
    "LaptopCover": false,
    "NightstandLamp": false,
    "ComfortCushion": true,
    "TCWW1": true,
    "TCWW2": false
  },
  {
    "name": "KANG Lia",
    "prodigy": "Vestenium",
    "recipient": "Vestenium dorm",
    "message": "Semangaat nordee \nSemangat vesteee\nSemangat osteeen \nSemangat sydeen",
    "HomeLivingSet": true,
    "ElectronicSet": true,
    "AccessoriesSet": true,
    "StationarySet": true,
    "PCSet1": true,
    "PCSet2": true,
    "Headphone": true,
    "PassportCover": true,
    "LaptopCover": true,
    "NightstandLamp": true,
    "ComfortCushion": true,
    "TCWW1": false,
    "TCWW2": true
  },
  {
    "name": "LEE Manda",
    "prodigy": "Vestenium",
    "recipient": "Vestenium",
    "message": "SEMANGAT VESTE",
    "HomeLivingSet": true,
    "ElectronicSet": true,
    "AccessoriesSet": true,
    "StationarySet": true,
    "PCSet1": true,
    "PCSet2": true,
    "Headphone": true,
    "PassportCover": true,
    "LaptopCover": true,
    "NightstandLamp": true,
    "ComfortCushion": true,
    "TCWW1": true,
    "TCWW2": false
  },
  {
    "name": "KIM Araseli",
    "prodigy": "Vestenium",
    "recipient": "All Vestenians",
    "message": "For all Vestenians, this is for you.",
    "HomeLivingSet": false,
    "ElectronicSet": true,
    "AccessoriesSet": false,
    "StationarySet": false,
    "PCSet1": true,
    "PCSet2": false,
    "Headphone": false,
    "PassportCover": false,
    "LaptopCover": false,
    "NightstandLamp": false,
    "ComfortCushion": true,
    "TCWW1": false,
    "TCWW2": true
  },
  {
    "name": "LEE Gochujang",
    "prodigy": "Nordenium",
    "recipient": "1118 kintan rooms",
    "message": "Kintan,makasih banyak ya udah ngeladenin gue sejauh ini ya kintan. Kintan semangat terus...💙🤘",
    "HomeLivingSet": false,
    "ElectronicSet": false,
    "AccessoriesSet": true,
    "StationarySet": false,
    "PCSet1": true,
    "PCSet2": false,
    "Headphone": false,
    "PassportCover": false,
    "LaptopCover": true,
    "NightstandLamp": false,
    "ComfortCushion": false,
    "TCWW1": false,
    "TCWW2": true
  },
  {
    "name": "YOON Charis",
    "prodigy": "Vestenium",
    "recipient": "Vestenium Dormitory",
    "message": "Dear all vesten, sayanghae❤",
    "HomeLivingSet": false,
    "ElectronicSet": false,
    "AccessoriesSet": true,
    "StationarySet": false,
    "PCSet1": false,
    "PCSet2": true,
    "Headphone": false,
    "PassportCover": true,
    "LaptopCover": true,
    "NightstandLamp": false,
    "ComfortCushion": true,
    "TCWW1": true,
    "TCWW2": false
  },
  {
    "name": "LEE Qila",
    "prodigy": "Sydenium",
    "recipient": "Sydenium",
    "message": "Love you, Sydenians! ❤",
    "HomeLivingSet": true,
    "ElectronicSet": true,
    "AccessoriesSet": true,
    "StationarySet": true,
    "PCSet1": true,
    "PCSet2": true,
    "Headphone": true,
    "PassportCover": true,
    "LaptopCover": true,
    "NightstandLamp": true,
    "ComfortCushion": true,
    "TCWW1": true,
    "TCWW2": false
  },
  {
    "name": "PARK Jinu",
    "prodigy": "Ostenium",
    "recipient": "LEE Gochujang dorm",
    "message": "Semangat!! Walaupun mimpi mu patah karena beberapa hal, jangan pernah merasa kalah!!",
    "HomeLivingSet": true,
    "ElectronicSet": false,
    "AccessoriesSet": false,
    "StationarySet": true,
    "PCSet1": true,
    "PCSet2": false,
    "Headphone": false,
    "PassportCover": true,
    "LaptopCover": true,
    "NightstandLamp": false,
    "ComfortCushion": false,
    "TCWW1": false,
    "TCWW2": true
  },
  {
    "name": "CHO Fiona",
    "prodigy": "Vestenium",
    "recipient": "kamarnya chofi langsung kaci yaaa? kacii",
    "message": "TO CHOFI FROM CHOFI, YOU DID WELL CHOFIII!!",
    "HomeLivingSet": false,
    "ElectronicSet": false,
    "AccessoriesSet": true,
    "StationarySet": false,
    "PCSet1": false,
    "PCSet2": true,
    "Headphone": false,
    "PassportCover": false,
    "LaptopCover": false,
    "NightstandLamp": true,
    "ComfortCushion": false,
    "TCWW1": true,
    "TCWW2": false
  },
  {
    "name": "SON Aline",
    "prodigy": "Ostenium",
    "recipient": "Kamar 229, Asrama Ostenium",
    "message": "Hai 229",
    "HomeLivingSet": true,
    "ElectronicSet": true,
    "AccessoriesSet": true,
    "StationarySet": true,
    "PCSet1": true,
    "PCSet2": true,
    "Headphone": true,
    "PassportCover": true,
    "LaptopCover": true,
    "NightstandLamp": true,
    "ComfortCushion": true,
    "TCWW1": true,
    "TCWW2": false
  },
  {
    "name": "LEE Gochujang",
    "prodigy": "Nordenium",
    "recipient": "Room LEE Ayin 🤘",
    "message": "Ayin,Terima kasih banyak udah support gue sejauh ini terus udah mau nyimak gue selama jelasin materi,ayinnnn seneng bgt bisa kenalan sama Ayin. Thank you so much ya💙",
    "HomeLivingSet": false,
    "ElectronicSet": false,
    "AccessoriesSet": false,
    "StationarySet": true,
    "PCSet1": true,
    "PCSet2": false,
    "Headphone": false,
    "PassportCover": false,
    "LaptopCover": true,
    "NightstandLamp": false,
    "ComfortCushion": false,
    "TCWW1": false,
    "TCWW2": true
  },
  {
    "name": "LEE Rani",
    "prodigy": "Sydenium",
    "recipient": "Yoon Sanha - Sydenium",
    "message": "Hope you'll like it, have a great day! ^^",
    "HomeLivingSet": true,
    "ElectronicSet": true,
    "AccessoriesSet": true,
    "StationarySet": true,
    "PCSet1": true,
    "PCSet2": true,
    "Headphone": true,
    "PassportCover": true,
    "LaptopCover": true,
    "NightstandLamp": true,
    "ComfortCushion": true,
    "TCWW1": true,
    "TCWW2": false
  },
  {
    "name": "CHOI Jessie",
    "prodigy": "Vestenium",
    "recipient": "Send it to NA Jaemin please",
    "message": "Have a great week, jaem! don’t skip your meals yaa",
    "HomeLivingSet": false,
    "ElectronicSet": true,
    "AccessoriesSet": false,
    "StationarySet": false,
    "PCSet1": false,
    "PCSet2": true,
    "Headphone": false,
    "PassportCover": false,
    "LaptopCover": true,
    "NightstandLamp": false,
    "ComfortCushion": false,
    "TCWW1": false,
    "TCWW2": true
  },
  {
    "name": "KIM Elena",
    "prodigy": "Vestenium",
    "recipient": "KIM Araseli, CHO Fiona, SEO Alexa, KWON Chessa",
    "message": "Gue gak nyesel ketemu kalian, soalnya kalian jmtieeeee",
    "HomeLivingSet": true,
    "ElectronicSet": false,
    "AccessoriesSet": false,
    "StationarySet": false,
    "PCSet1": false,
    "PCSet2": true,
    "Headphone": false,
    "PassportCover": false,
    "LaptopCover": false,
    "NightstandLamp": true,
    "ComfortCushion": false,
    "TCWW1": true,
    "TCWW2": false
  },
  {
    "name": "LEE Haidar",
    "prodigy": "Ostenium",
    "recipient": "Lee Yeseul",
    "message": "semangat kembar kembar norde gue.",
    "HomeLivingSet": true,
    "ElectronicSet": true,
    "AccessoriesSet": true,
    "StationarySet": true,
    "PCSet1": true,
    "PCSet2": true,
    "Headphone": true,
    "PassportCover": true,
    "LaptopCover": true,
    "NightstandLamp": true,
    "ComfortCushion": true,
    "TCWW1": true,
    "TCWW2": false
  },
  {
    "name": "LEE MALIQ",
    "prodigy": "Vestenium",
    "recipient": "My room",
    "message": "Dari maliq untuk maliq",
    "HomeLivingSet": true,
    "ElectronicSet": true,
    "AccessoriesSet": true,
    "StationarySet": true,
    "PCSet1": true,
    "PCSet2": false,
    "Headphone": true,
    "PassportCover": false,
    "LaptopCover": true,
    "NightstandLamp": true,
    "ComfortCushion": false,
    "TCWW1": true,
    "TCWW2": false
  },
  {
    "name": "im Hyerin",
    "prodigy": "Sydenium",
    "recipient": "Im Hyerin",
    "message": "To myself: be strong.",
    "HomeLivingSet": false,
    "ElectronicSet": true,
    "AccessoriesSet": false,
    "StationarySet": true,
    "PCSet1": false,
    "PCSet2": true,
    "Headphone": false,
    "PassportCover": false,
    "LaptopCover": true,
    "NightstandLamp": true,
    "ComfortCushion": true,
    "TCWW1": true,
    "TCWW2": false
  },
  {
    "name": "KIM Raejoon",
    "prodigy": "Sydenium",
    "recipient": "sydenium",
    "message": "💙💙💙",
    "HomeLivingSet": true,
    "ElectronicSet": true,
    "AccessoriesSet": true,
    "StationarySet": true,
    "PCSet1": true,
    "PCSet2": true,
    "Headphone": true,
    "PassportCover": true,
    "LaptopCover": true,
    "NightstandLamp": true,
    "ComfortCushion": true,
    "TCWW1": false,
    "TCWW2": true
  },
  {
    "name": "Jung Baera",
    "prodigy": "Sydenium",
    "recipient": "Someone",
    "message": "To someone make me smile\nTerimakasih telah hadir, terlebih untuk anak syde, bersyukur banget aku bisa menjadi bagian dari kalian, untuk anak yang aku sebutkan tadi, jaga kesehatan, ingat kamu harus nunjukin pada semesta kalo kamu berharga, keep smile and never give up😊",
    "HomeLivingSet": false,
    "ElectronicSet": true,
    "AccessoriesSet": false,
    "StationarySet": false,
    "PCSet1": false,
    "PCSet2": true,
    "Headphone": true,
    "PassportCover": true,
    "LaptopCover": true,
    "NightstandLamp": false,
    "ComfortCushion": false,
    "TCWW1": false,
    "TCWW2": true
  },
  {
    "name": "PARK Aruna",
    "prodigy": "Nordenium",
    "recipient": "All",
    "message": "Love you all guys",
    "HomeLivingSet": false,
    "ElectronicSet": false,
    "AccessoriesSet": true,
    "StationarySet": false,
    "PCSet1": false,
    "PCSet2": true,
    "Headphone": true,
    "PassportCover": true,
    "LaptopCover": true,
    "NightstandLamp": true,
    "ComfortCushion": true,
    "TCWW1": false,
    "TCWW2": true
  },
  {
    "name": "LEE Gochujang",
    "prodigy": "Nordenium",
    "recipient": "Ruangan HRD N",
    "message": "Budhe hardiN maaf kalo saya selama ini banyak salah ngomong,terima kasih juga sudah menemani kebadutan dan rela kita badutin. Budhe makasih banyak,sayang budhe banyak banyak. Terima kasih dan maaf karna kita kadang suka kelewatan. WE NORDEN YOU BUDHE💙🤟",
    "HomeLivingSet": false,
    "ElectronicSet": false,
    "AccessoriesSet": true,
    "StationarySet": false,
    "PCSet1": false,
    "PCSet2": true,
    "Headphone": false,
    "PassportCover": false,
    "LaptopCover": false,
    "NightstandLamp": false,
    "ComfortCushion": true,
    "TCWW1": true,
    "TCWW2": false
  },
  {
    "name": "PARK Aya",
    "prodigy": "Vestenium",
    "recipient": "kamar aya, nomor 1270 ya☺",
    "message": "semangat norde! jadikan aku seer👁👄👁",
    "HomeLivingSet": false,
    "ElectronicSet": false,
    "AccessoriesSet": true,
    "StationarySet": false,
    "PCSet1": false,
    "PCSet2": true,
    "Headphone": true,
    "PassportCover": false,
    "LaptopCover": false,
    "NightstandLamp": false,
    "ComfortCushion": false,
    "TCWW1": true,
    "TCWW2": false
  },
  {
    "name": "Jung Chala",
    "prodigy": "Sydenium",
    "recipient": "Sydenium's dorm",
    "message": "NORDE JJANG!",
    "HomeLivingSet": false,
    "ElectronicSet": false,
    "AccessoriesSet": true,
    "StationarySet": false,
    "PCSet1": false,
    "PCSet2": true,
    "Headphone": true,
    "PassportCover": false,
    "LaptopCover": true,
    "NightstandLamp": false,
    "ComfortCushion": false,
    "TCWW1": false,
    "TCWW2": true
  },
  {
    "name": "LEE ace",
    "prodigy": "Vestenium",
    "recipient": "Lee Ace",
    "message": "hai diriku! nih liat aku beliin, udh ya! nanti yg baca ini ngakak☺️ salam rrrawrh😠",
    "HomeLivingSet": false,
    "ElectronicSet": false,
    "AccessoriesSet": true,
    "StationarySet": false,
    "PCSet1": false,
    "PCSet2": true,
    "Headphone": true,
    "PassportCover": true,
    "LaptopCover": true,
    "NightstandLamp": true,
    "ComfortCushion": true,
    "TCWW1": false,
    "TCWW2": true
  },
  {
    "name": "KIM Ifa",
    "prodigy": "Vestenium",
    "recipient": "Vesten's lobby",
    "message": "Hmm.. I don't have specific message, actually. Just want to say that good luck for the comitte, don't forget to drink, eat, and sleep. Also keep happy!",
    "HomeLivingSet": true,
    "ElectronicSet": true,
    "AccessoriesSet": true,
    "StationarySet": true,
    "PCSet1": false,
    "PCSet2": true,
    "Headphone": true,
    "PassportCover": false,
    "LaptopCover": false,
    "NightstandLamp": false,
    "ComfortCushion": false,
    "TCWW1": false,
    "TCWW2": true
  },
  {
    "name": "KIM Awlia",
    "prodigy": "Vestenium",
    "recipient": "All",
    "message": "Enjoy! Hope you like it!",
    "HomeLivingSet": false,
    "ElectronicSet": false,
    "AccessoriesSet": true,
    "StationarySet": false,
    "PCSet1": false,
    "PCSet2": true,
    "Headphone": false,
    "PassportCover": false,
    "LaptopCover": false,
    "NightstandLamp": false,
    "ComfortCushion": false,
    "TCWW1": false,
    "TCWW2": true
  },
  {
    "name": "Kim Awlia",
    "prodigy": "Vestenium",
    "recipient": null,
    "message": "Enjoy! Hope you like it!",
    "HomeLivingSet": false,
    "ElectronicSet": false,
    "AccessoriesSet": true,
    "StationarySet": false,
    "PCSet1": false,
    "PCSet2": true,
    "Headphone": false,
    "PassportCover": false,
    "LaptopCover": false,
    "NightstandLamp": false,
    "ComfortCushion": false,
    "TCWW1": false,
    "TCWW2": true
  },
  {
    "name": "LEE Gochujang",
    "prodigy": "Nordenium",
    "recipient": "LEE Rii Rooms",
    "message": "Rii,seneng bisa liat rii lagi setelah kemaren sempet Hiatus ayo kita main lagi hahaha kangen rii 💙🤟",
    "HomeLivingSet": false,
    "ElectronicSet": false,
    "AccessoriesSet": true,
    "StationarySet": false,
    "PCSet1": true,
    "PCSet2": false,
    "Headphone": false,
    "PassportCover": true,
    "LaptopCover": false,
    "NightstandLamp": false,
    "ComfortCushion": false,
    "TCWW1": false,
    "TCWW2": true
  },
  {
    "name": "LEE Ocha",
    "prodigy": "Nordenium",
    "recipient": "lobby dormitory nordenium",
    "message": "Cheer up buat panitia nordanus kalo udah selese ntar gue traktir deh",
    "HomeLivingSet": false,
    "ElectronicSet": true,
    "AccessoriesSet": true,
    "StationarySet": false,
    "PCSet1": false,
    "PCSet2": true,
    "Headphone": true,
    "PassportCover": false,
    "LaptopCover": false,
    "NightstandLamp": false,
    "ComfortCushion": false,
    "TCWW1": true,
    "TCWW2": false
  },
  {
    "name": "Zhang Ayla",
    "prodigy": "Ostenium",
    "recipient": "Zhang Ayla",
    "message": "Cheer up! Have a good day ay",
    "HomeLivingSet": false,
    "ElectronicSet": true,
    "AccessoriesSet": false,
    "StationarySet": false,
    "PCSet1": false,
    "PCSet2": true,
    "Headphone": true,
    "PassportCover": false,
    "LaptopCover": false,
    "NightstandLamp": false,
    "ComfortCushion": false,
    "TCWW1": false,
    "TCWW2": true
  },
  {
    "name": "LEE Gochujang",
    "prodigy": "Nordenium",
    "recipient": "BAE Aera",
    "message": "Ayo kita berteman!! Jangan lupa gue asdos norde nanti ga gue kasih contekan lohhh",
    "HomeLivingSet": false,
    "ElectronicSet": false,
    "AccessoriesSet": true,
    "StationarySet": false,
    "PCSet1": true,
    "PCSet2": false,
    "Headphone": false,
    "PassportCover": true,
    "LaptopCover": false,
    "NightstandLamp": false,
    "ComfortCushion": false,
    "TCWW1": false,
    "TCWW2": true
  },
  {
    "name": "LEE Gochujang",
    "prodigy": "Nordenium",
    "recipient": "DO Elsa, Vestenium",
    "message": "Elsaaaa hahahaha gue ga bisa sweet sweetan sama lu. Tapi lucu aja bisa ketemu di NPA seneng bisa ngobrol lagi sama lu dan room chat kita dipenuhi dengan sumpah serampah hahahaha semoga bisa ketemu lagi ya Elsa 💙🤟",
    "HomeLivingSet": false,
    "ElectronicSet": true,
    "AccessoriesSet": false,
    "StationarySet": true,
    "PCSet1": true,
    "PCSet2": false,
    "Headphone": false,
    "PassportCover": false,
    "LaptopCover": false,
    "NightstandLamp": false,
    "ComfortCushion": true,
    "TCWW1": false,
    "TCWW2": true
  },
  {
    "name": "LEE Gochujang",
    "prodigy": "Nordenium",
    "recipient": "PARK Jinu,Ostenium",
    "message": "Denger denger dari panitia nordanus lu beliin gue sesuatu. Terima kasih banyak karena lu udah mau support gue dari Senin sampe rela nginep karena belakangan ini gue down terlebih masalah mimpi gue yang gagal gue capai, gue berterima kasih banyak. Emang kadang lu nyebelin aja jadi gue males nanggepin lu di NPA hahaha. Jinu thank you💛",
    "HomeLivingSet": false,
    "ElectronicSet": false,
    "AccessoriesSet": true,
    "StationarySet": true,
    "PCSet1": true,
    "PCSet2": true,
    "Headphone": true,
    "PassportCover": false,
    "LaptopCover": false,
    "NightstandLamp": true,
    "ComfortCushion": false,
    "TCWW1": false,
    "TCWW2": true
  },
  {
    "name": "Cireng",
    "prodigy": "Nordenium",
    "recipient": "Nordenium Dorm",
    "message": "BUAT SEMUA NORDENIANS KESAYANGAN AKOOOOO💙💙💙💙💙💙",
    "HomeLivingSet": true,
    "ElectronicSet": true,
    "AccessoriesSet": true,
    "StationarySet": true,
    "PCSet1": true,
    "PCSet2": false,
    "Headphone": false,
    "PassportCover": false,
    "LaptopCover": false,
    "NightstandLamp": false,
    "ComfortCushion": true,
    "TCWW1": true,
    "TCWW2": false
  },
  {
    "name": "LEE Ayin",
    "prodigy": "Nordenium",
    "recipient": "dorm\nNG-2579",
    "message": "~",
    "HomeLivingSet": true,
    "ElectronicSet": true,
    "AccessoriesSet": true,
    "StationarySet": true,
    "PCSet1": true,
    "PCSet2": true,
    "Headphone": true,
    "PassportCover": true,
    "LaptopCover": true,
    "NightstandLamp": true,
    "ComfortCushion": true,
    "TCWW1": true,
    "TCWW2": false
  }
  {
    "name": "Anonym",
    "prodigy": "Nordenium",
    "recipient": "Staff Nordanus",
    "message": "Thank you for your hard work! Ingat, kalian semua semerbak yang masing-masing punya identitas aromanya sendiri-sendiri. Taman bunga indah karena beragam jenisnya, bukan karena jumlahnya saja ^^ Terus berkreasi ya!",
    "HomeLivingSet": true,
    "ElectronicSet": true,
    "AccessoriesSet": true,
    "StationarySet": true,
    "PCSet1": true,
    "PCSet2": true,
    "Headphone": true,
    "PassportCover": true,
    "LaptopCover": true,
    "NightstandLamp": true,
    "ComfortCushion": true,
    "TCWW1": true,
    "TCWW2": false
  }
];

function sanitizeUTF8(text) {
    if (!text) return "";

    var output = "";
    for (var i=0; i<text.length; i++) {
        if (text.charCodeAt(i) <= 127 || text.charCodeAt(i) >= 160 && text.charCodeAt(i) <= 255) {
            output += text.charAt(i);
        }
    }
    return output.toLowerCase().replace(/\s/g, "-");
}

const dataset = Object.fromEntries(
    jsonList.map(entry => [sanitizeUTF8(entry.name) + "|" + sanitizeUTF8(entry.recipient), entry])
);